#!/bin/bash

#grant executable to script
chmod +x /usr/local/bin/dataone-cn-version-tool

## Update DateONE Version Info Doc
java -jar /usr/share/dataone-cn-version-tool/dataone-cn-version-tool.jar -F/usr/share/dataone-cn-version-tool/version-tool.properties -html > /var/www/cn-version.html

exit 0
